// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabalhoCertificado.Data;

namespace TrabalhoCertificado.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201207160151_migra05")]
    partial class migra05
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrabalhoCertificado.Models.RecuperarSenhaLinks", b =>
                {
                    b.Property<string>("IDEncry")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("tempo")
                        .HasColumnType("datetime2");

                    b.HasKey("IDEncry");

                    b.ToTable("TBRecuperarSenhaLinks");
                });

            modelBuilder.Entity("TrabalhoCertificado.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ativado")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("previlegios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senhaEncry")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TBUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
